spring:
  datasource:
    druid:
      cndb:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.201.116.61:3306/center_mix_cn_dgslg?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
        username: admin
        password: admin#4399
      globaldb:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.128.3.57:3306/center_mix_global_dgslg?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
        username: admin
        password: admin#4399
      globaltsdb:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.132.251.185:3306/center_mix_globalts_dgslg?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
        username: admin
        password: admin#4399
      androiddb:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://120.31.71.12:3306/center_android_cn_dgslg?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
        username: admin
        password: admin#4399

      targetdb:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.201.84.56:3308/DgslgMineDB?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
        username: admin
        password: admin#4399

      initial-size: 5
      minIdle: 5
      #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 20
      #     最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      #     配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      #     设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      #     设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      #     可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      #     保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize:   20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      db-type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8822

listening_path:
  /data/web/uploadFile/dgslg/mix_cn,
  /data/web/uploadFile/dgslg/android_cn,
  /data/web/uploadFile/dgslg/mix_globalts,
  /data/web/uploadFile/dgslg/mix_global,
  /data/web/uploadFile/dgslg/mix_cnts

regular_expression:
  ^dgslg\S+\_error\_msg\.dat\.zip

origin_ip:
  101.32.11.14

err_type:
  SYS_ERROR,
  ERROR,
  SYS_EXCEPT

mybatis:
  type-aliases-package: model.filtererr.pojo
